image: docker:latest
stages:
  - deploy
services:
  - docker:18.09.8-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  REGISTRY_NAME: registry.gitlab.com
  CONTAINER_IMAGE_NAME: registry.gitlab.com/yerkebulan.k/vic
  CONTAINER_CURRENT_IMAGE_NAME: $CONTAINER_IMAGE_NAME:$CI_COMMIT_REF_SLUG


.build_project: &build_project
  tags:
    - docker
  stage: deploy
  before_script:
   - sed -i 's/dl-cdn.alpinelinux.org/mirror.neolabs.kz/g' /etc/apk/repositories
   - 'which ssh-agent || ( apk update && apk add -qq openssh )'
   - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | ssh-add - && mkdir -p ~/.ssh
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_NAME
    - docker build -t $CONTAINER_CURRENT_IMAGE_NAME .
    # - scp -rp $LOCAL_PATH root@$DEPLOY_HOST:$DEPLOY_PATH
    - docker push $CONTAINER_CURRENT_IMAGE_NAME
    - ssh  root@$DEPLOY_HOST "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_NAME && 
      cd $DEPLOY_PATH && docker-compose down -v && docker-compose up -d && docker system prune -f -a"


deploy:
 variables:
   DEPLOY_HOST: "srh.org.kz"
   DEPLOY_PATH: "/srv/vic/"
   LOCAL_PATH: "src/dist"
 <<: *build_project
 only:
   - dev

# .deploy_project: &deploy_project
#  tags:
#    - docker
#  stage: deploy
#  before_script:
#    - sed -i 's/dl-cdn.alpinelinux.org/mirror.neolabs.kz/g' /etc/apk/repositories
#    - 'which ssh-agent || ( apk update && apk add -qq openssh )'
#    - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | ssh-add - && mkdir -p ~/.ssh
#    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#  script:
#    - scp -rp $LOCAL_PATH root@$DEPLOY_HOST:$DEPLOY_PATH
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_NAME


# deploy_prod:
#  variables:
#    DEPLOY_HOST: "srh.org.kz"
#    DEPLOY_PATH: "/srv/vic/"
#    LOCAL_PATH: "dist"
#  <<: *deploy_project
#  only:
#    - develop
